baseURL = "https://www.jongregory.net/"
languageCode = "en-us"
title = "Jon Gregory"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
pygmentsUseClasses=true

[params]
    author = "Jon Gregory"
    description = "Technical Architect"
    githubUsername = "jongregory"
    accent = "teal"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    css = ["/css/syntax.css"]
	profilepic = "/images/jonprofile.jpg"
    #highlight = false
    #highlightStyle = "solarized-dark"
    #highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3
	
[[menu.main]]
    url = "/OlderPosts/"
    name = "Older Posts"
    weight = 4
	
[[menu.main]]
    url = "/pages/"
    name = "Pages"
    weight = 5
	

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jon.gregory@live.co.uk"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jongregory/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jongregory77/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jonathan-gregory-78664587/"
    name = "linkedin"
    weight = 4

##[[menu.icon]]
##    url = "https://www.stackoverflow.com/username/"
##    name = "stack-overflow"
##    weight = 5

